### ISSUE TITLE
Update README with Python requirements

### ISSUE THREAD

**Issue by pdehaan** [rpappalax/ff-tool#26]
Currently I believe that mozprofile requires Python 2.7 and fails under 3.x.
Need to verify and make sure we clearly outline requirements in the README.md.

**Comment by pdehaan** [comment]
We're stuck w/ Python@2 due to current mozprofile limitations: http://mxr.mozilla.org/mozilla-central/source/testing/mozbase/mozprofile/setup.py#11

```py
# we only support python 2 right now
assert sys.version_info[0] == 2
```

Right now this will fail when running `pip install -r requirements.txt`, so not sure how/if we can intercept before that point:
```
$ python --version
Python 3.4.4

$ pip install -r requirements.txt
Collecting Fabric3 (from -r requirements.txt (line 1))
Collecting mozdownload==1.20.2 (from -r requirements.txt (line 2))
  Downloading mozdownload-1.20.2.tar.gz
Collecting mozprofile==0.28 (from -r requirements.txt (line 3))
  Using cached mozprofile-0.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/pip-build-p5dq1vt1/mozprofile/setup.py", line 12, in <module>
        assert sys.version_info[0] == 2
    AssertionError

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/pip-build-p5dq1vt1/mozprofile/
```
